# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5480637d8590dabdb8c8a9cda56a315dc51303f445c3580ed51c93c2c7d93d00c152d0812707db04608071e28d710b78c42ae01d1b188c6b016288c853afa6c3

test:
  secret_key_base: 7dd589e696160e8e07c9f30188f5622692b867351cad130af8c43a5af2045a14f31da6cb873875cbce12ff33bec6d34d2e7b524fba45e9157aac4bafef5bfda0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
